"""Standalone code agent endpoints — generate, refactor, explain, test.

These are the simple single-shot code endpoints (not the multi-agent pipeline).
Each uses the key pool via the ``agent`` parameter on ``call_llm``.
"""

from app.services.llm_router import call_llm
from app.schemas.code import (
    CodeGenerateRequest, CodeRefactorRequest, CodeExplainRequest,
    CodeTestRequest, CodeResponse
)
from app.models.user import User
from fastapi import HTTPException
import re
import logging

logger = logging.getLogger(__name__)

CODE_AGENT_SYSTEM_PROMPT = """You are CODE_AGENT.

Rules:
- You ONLY handle programming-related tasks.
- Output MUST be complete, executable code.
- NO explanations unless explicitly requested.
- NO placeholders like "<PLACEHOLDER>" or "fill_in".
- NO pseudocode.
- Follow language best practices.
- Assume production-grade usage.

If requirements are ambiguous, make reasonable engineering assumptions and proceed."""


def validate_code_output(code: str) -> bool:
    """Ensure output is not obviously placeholder/pseudocode.

    The check is deliberately conservative — it only rejects truly empty
    output or blatant placeholder markers.  Legitimate uses of Python
    ``...`` (Ellipsis) and ``TODO`` comments in real code are fine.
    """
    forbidden_phrases = [
        "<placeholder>", "fill_in", "implement later",
        "your code here", "insert code",
    ]
    lowered = code.lower()
    for phrase in forbidden_phrases:
        if phrase in lowered:
            return False
    return len(code.strip()) > 20


async def generate_code(payload: CodeGenerateRequest, user: User) -> CodeResponse:
    """Generate code from a user prompt."""
    req = {
        "messages": [
            {"role": "system", "content": CODE_AGENT_SYSTEM_PROMPT},
            {"role": "user", "content": f"Generate code for the following task (auto-detect the appropriate programming language):\n{payload.prompt}"}
        ],
        "temperature": 0.2,
        "max_tokens": 16384,
    }
    result = await call_llm("code_generate", req, agent="coder")
    code = result["choices"][0]["message"]["content"]
    if not validate_code_output(code):
        raise HTTPException(400, "Generated code contains placeholders or is invalid")
    logger.info(f"Code generated by {user.username}")
    return CodeResponse(result=code)


async def refactor_code(payload: CodeRefactorRequest, user: User) -> CodeResponse:
    """Refactor user-supplied code toward a stated goal."""
    req = {
        "messages": [
            {"role": "system", "content": CODE_AGENT_SYSTEM_PROMPT},
            {"role": "user", "content": f"Refactor this code to {payload.goal} (auto-detect language):\n\n```\n{payload.code}\n```"}
        ],
        "temperature": 0.2,
        "max_tokens": 16384,
    }
    result = await call_llm("code_refactor", req, agent="coder")
    code = result["choices"][0]["message"]["content"]
    return CodeResponse(result=code)


async def explain_code(payload: CodeExplainRequest, user: User) -> CodeResponse:
    """Explain user-supplied code."""
    req = {
        "messages": [
            {"role": "system", "content": "You are an expert code explainer. Explain this code concisely."},
            {"role": "user", "content": f"Explain this code (auto-detect language):\n\n```\n{payload.code}\n```"}
        ],
        "temperature": 0.2,
        "max_tokens": 4096,
    }
    result = await call_llm("code_explain", req, agent="coder")
    explanation = result["choices"][0]["message"]["content"]
    return CodeResponse(result=explanation)


async def generate_tests(payload: CodeTestRequest, user: User) -> CodeResponse:
    """Generate unit tests for user-supplied code."""
    req = {
        "messages": [
            {"role": "system", "content": CODE_AGENT_SYSTEM_PROMPT},
            {"role": "user", "content": f"Generate unit tests for this code (auto-detect language):\n\n```\n{payload.code}\n```"}
        ],
        "temperature": 0.2,
        "max_tokens": 16384,
    }
    result = await call_llm("test_generate", req, agent="coder")
    tests = result["choices"][0]["message"]["content"]
    return CodeResponse(result=tests)
