"""baseline schema

Revision ID: 5aa1539be597
Revises: 
Create Date: 2026-07-30 11:43:12.143203
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.models.types

# revision identifiers, used by Alembic.
revision: str = '5aa1539be597'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_permissions',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_permissions_name'), 'admin_permissions', ['name'], unique=True)
    op.create_table('admin_roles',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hierarchy_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_roles_name'), 'admin_roles', ['name'], unique=True)
    op.create_table('ai_models',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('endpoint_url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('fallback_model_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['fallback_model_id'], ['ai_models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_models_model_name'), 'ai_models', ['model_name'], unique=True)
    op.create_table('auto_healing_events',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('is_successful', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_retention_policies',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('scope', sa.Enum('ORGANIZATION', 'WORKSPACE', 'GLOBAL', name='retentionscope'), nullable=True),
    sa.Column('target_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('created_by', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_retention_policies_target_id'), 'data_retention_policies', ['target_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('ai_limits', app.models.types.JSONB(), nullable=True),
    sa.Column('feature_flags', app.models.types.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('otp_codes',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('password_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_email'), 'otp_codes', ['email'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_monthly', sa.Integer(), nullable=False),
    sa.Column('price_annual', sa.Integer(), nullable=False),
    sa.Column('limits', app.models.types.JSONB(), nullable=False),
    sa.Column('features', app.models.types.JSONB(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin_plan', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('download_url', sa.String(), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_updates_id'), 'system_updates', ['id'], unique=False)
    op.create_table('admin_role_permissions',
    sa.Column('role_id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('permission_id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['admin_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['admin_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('ai_firewall_policies',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('org_id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('block_topics_keywords', app.models.types.ArrayType(), nullable=True),
    sa.Column('risk_threshold', sa.Float(), nullable=True),
    sa.Column('auto_quarantine_users', sa.Boolean(), nullable=True),
    sa.Column('pii_redaction_enabled', sa.Boolean(), nullable=True),
    sa.Column('custom_rules', app.models.types.JSONB(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_firewall_policies_org_id'), 'ai_firewall_policies', ['org_id'], unique=False)
    op.create_table('business_metrics_daily',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('org_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('active_users', sa.Integer(), nullable=True),
    sa.Column('messages_sent', sa.Integer(), nullable=True),
    sa.Column('voice_segments_generated', sa.Integer(), nullable=True),
    sa.Column('rag_queries', sa.Integer(), nullable=True),
    sa.Column('code_executions', sa.Integer(), nullable=True),
    sa.Column('date_recorded', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_metrics_daily_date_recorded'), 'business_metrics_daily', ['date_recorded'], unique=False)
    op.create_index(op.f('ix_business_metrics_daily_org_id'), 'business_metrics_daily', ['org_id'], unique=False)
    op.create_table('latency_metrics',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('org_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('ttft_ms', sa.Float(), nullable=True),
    sa.Column('total_time_ms', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_latency_metrics_org_id'), 'latency_metrics', ['org_id'], unique=False)
    op.create_index(op.f('ix_latency_metrics_timestamp'), 'latency_metrics', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', name='roleenum'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('organization_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('settings', app.models.types.JSONB(), nullable=True),
    sa.Column('totp_secret', sa.String(), nullable=True),
    sa.Column('is_mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('org_id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rag_collection_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rag_collection_name')
    )
    op.create_index(op.f('ix_workspaces_name'), 'workspaces', ['name'], unique=False)
    op.create_table('admin_profiles',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('role_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'EXPIRED', name='adminstatus'), nullable=True),
    sa.Column('access_expires_at', sa.DateTime(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('created_by_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['admin_roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('workspace', sa.String(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('content', app.models.utils.EncryptedText(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_id'), 'memories', ['id'], unique=False)
    op.create_table('personal_access_tokens',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('scopes', app.models.types.JSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_access_tokens_token_hash'), 'personal_access_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_personal_access_tokens_user_id'), 'personal_access_tokens', ['user_id'], unique=False)
    op.create_table('rag_evaluations',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('query_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('org_id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('workspace_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('groundedness_score', sa.Float(), nullable=True),
    sa.Column('context_overlap_pct', sa.Float(), nullable=True),
    sa.Column('retrieval_latency_ms', sa.Integer(), nullable=True),
    sa.Column('top_k_used', sa.Integer(), nullable=True),
    sa.Column('chunk_metadata', app.models.types.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_evaluations_created_at'), 'rag_evaluations', ['created_at'], unique=False)
    op.create_index(op.f('ix_rag_evaluations_org_id'), 'rag_evaluations', ['org_id'], unique=False)
    op.create_index(op.f('ix_rag_evaluations_query_id'), 'rag_evaluations', ['query_id'], unique=False)
    op.create_index(op.f('ix_rag_evaluations_workspace_id'), 'rag_evaluations', ['workspace_id'], unique=False)
    op.create_table('snippets',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_activity_logs',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('org_id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_activity_logs_model_name'), 'token_activity_logs', ['model_name'], unique=False)
    op.create_index(op.f('ix_token_activity_logs_org_id'), 'token_activity_logs', ['org_id'], unique=False)
    op.create_index(op.f('ix_token_activity_logs_timestamp'), 'token_activity_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_token_activity_logs_user_id'), 'token_activity_logs', ['user_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('requests_count', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_date'), 'usage_records', ['date'], unique=False)
    op.create_index(op.f('ix_usage_records_feature'), 'usage_records', ['feature'], unique=False)
    op.create_index(op.f('ix_usage_records_month'), 'usage_records', ['month'], unique=False)
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('refresh_token_hash', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('plan_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED', 'TRIAL', name='subscriptionstatus'), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_admin_assigned', sa.Boolean(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_audit_logs',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('admin_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('old_state', app.models.types.JSONB(), nullable=True),
    sa.Column('new_state', app.models.types.JSONB(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_logs_action'), 'admin_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_timestamp'), 'admin_audit_logs', ['timestamp'], unique=False)
    op.create_table('admin_device_fingerprints',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('admin_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('fingerprint_hash', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_trusted', sa.Boolean(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint_hash')
    )
    op.create_index(op.f('ix_admin_device_fingerprints_admin_id'), 'admin_device_fingerprints', ['admin_id'], unique=False)
    op.create_table('admin_invites',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('invited_by_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('assigned_role_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED', name='invitestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_role_id'], ['admin_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_id'], ['admin_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_invites_email'), 'admin_invites', ['email'], unique=False)
    op.create_table('admin_pending_actions',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('initiator_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('payload', app.models.types.JSONB(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='actionstatus'), nullable=True),
    sa.Column('approver_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['admin_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['initiator_id'], ['admin_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_profile_permissions',
    sa.Column('admin_id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('permission_id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['admin_permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('admin_id', 'permission_id')
    )
    op.create_table('admin_sessions',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('admin_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('refresh_token_hash', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('session_id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', app.models.utils.EncryptedText(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_tickets',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.Enum('TRIAGE', 'INVESTIGATING', 'MITIGATED', 'RESOLVED', name='incidentstatus'), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('assigned_admin_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('org_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('audit_log_uuids', app.models.types.JSONB(), nullable=True),
    sa.Column('resolution_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['admin_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_tickets_status'), 'incident_tickets', ['status'], unique=False)
    op.create_table('jit_privileges',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('admin_id', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('requested_role', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('approved_by', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by'], ['admin_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jit_privileges_admin_id'), 'jit_privileges', ['admin_id'], unique=False)
    op.create_table('plugin_registry',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', app.models.types.UUID(as_uuid=True), nullable=True),
    sa.Column('required_permissions', app.models.types.JSONB(), nullable=True),
    sa.Column('execute_in_sandbox', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['admin_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_registry_name'), 'plugin_registry', ['name'], unique=True)
    op.create_table('shared_chats',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('session_id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('share_token', sa.String(), nullable=False),
    sa.Column('snapshot_json', app.models.utils.EncryptedJSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('org_plugin_configurations',
    sa.Column('id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('org_id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('plugin_id', app.models.types.UUID(as_uuid=True), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('config_params', app.models.types.JSONB(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugin_registry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('org_plugin_configurations')
    op.drop_table('shared_chats')
    op.drop_index(op.f('ix_plugin_registry_name'), table_name='plugin_registry')
    op.drop_table('plugin_registry')
    op.drop_index(op.f('ix_jit_privileges_admin_id'), table_name='jit_privileges')
    op.drop_table('jit_privileges')
    op.drop_index(op.f('ix_incident_tickets_status'), table_name='incident_tickets')
    op.drop_table('incident_tickets')
    op.drop_table('chat_messages')
    op.drop_table('admin_sessions')
    op.drop_table('admin_profile_permissions')
    op.drop_table('admin_pending_actions')
    op.drop_index(op.f('ix_admin_invites_email'), table_name='admin_invites')
    op.drop_table('admin_invites')
    op.drop_index(op.f('ix_admin_device_fingerprints_admin_id'), table_name='admin_device_fingerprints')
    op.drop_table('admin_device_fingerprints')
    op.drop_index(op.f('ix_admin_audit_logs_timestamp'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_action'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_month'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_feature'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_date'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_token_activity_logs_user_id'), table_name='token_activity_logs')
    op.drop_index(op.f('ix_token_activity_logs_timestamp'), table_name='token_activity_logs')
    op.drop_index(op.f('ix_token_activity_logs_org_id'), table_name='token_activity_logs')
    op.drop_index(op.f('ix_token_activity_logs_model_name'), table_name='token_activity_logs')
    op.drop_table('token_activity_logs')
    op.drop_table('snippets')
    op.drop_index(op.f('ix_rag_evaluations_workspace_id'), table_name='rag_evaluations')
    op.drop_index(op.f('ix_rag_evaluations_query_id'), table_name='rag_evaluations')
    op.drop_index(op.f('ix_rag_evaluations_org_id'), table_name='rag_evaluations')
    op.drop_index(op.f('ix_rag_evaluations_created_at'), table_name='rag_evaluations')
    op.drop_table('rag_evaluations')
    op.drop_index(op.f('ix_personal_access_tokens_user_id'), table_name='personal_access_tokens')
    op.drop_index(op.f('ix_personal_access_tokens_token_hash'), table_name='personal_access_tokens')
    op.drop_table('personal_access_tokens')
    op.drop_index(op.f('ix_memories_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_table('files')
    op.drop_table('chat_sessions')
    op.drop_table('admin_profiles')
    op.drop_index(op.f('ix_workspaces_name'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_latency_metrics_timestamp'), table_name='latency_metrics')
    op.drop_index(op.f('ix_latency_metrics_org_id'), table_name='latency_metrics')
    op.drop_table('latency_metrics')
    op.drop_index(op.f('ix_business_metrics_daily_org_id'), table_name='business_metrics_daily')
    op.drop_index(op.f('ix_business_metrics_daily_date_recorded'), table_name='business_metrics_daily')
    op.drop_table('business_metrics_daily')
    op.drop_index(op.f('ix_ai_firewall_policies_org_id'), table_name='ai_firewall_policies')
    op.drop_table('ai_firewall_policies')
    op.drop_table('admin_role_permissions')
    op.drop_index(op.f('ix_system_updates_id'), table_name='system_updates')
    op.drop_table('system_updates')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_otp_codes_email'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_data_retention_policies_target_id'), table_name='data_retention_policies')
    op.drop_table('data_retention_policies')
    op.drop_table('auto_healing_events')
    op.drop_index(op.f('ix_ai_models_model_name'), table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_index(op.f('ix_admin_roles_name'), table_name='admin_roles')
    op.drop_table('admin_roles')
    op.drop_index(op.f('ix_admin_permissions_name'), table_name='admin_permissions')
    op.drop_table('admin_permissions')
    # ### end Alembic commands ###
